image: openjdk:11
stages:
  - check_deleted_files

check_deleted_files:
  stage: check_deleted_files
  script:
    - git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA > deleted_files.txt
    - if [ -s deleted_files.txt ]; then echo "Deleted files found:" && cat deleted_files.txt; else echo "No files deleted."; fi
  only:
    changes:
      - '**/*'

