image: openjdk:11
stages:
  - build
  - test


build:
  stage: build
  script:
    - chmod +x ./gradlew
    - echo "y" | sdkmanager --licenses
    - ./gradlew assembleDebug
   
  artifacts:
    paths:
      - app/build/outputs/

test:
  stage: test
  script:
    - echo "Running tests..."
  dependencies:
    - build

