image: openjdk:17
stages:
  - build
  - test


build:
  stage: build
  script:
    - chmod +x ./gradlew
    - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses
    - ./gradlew assembleDebug
   
  artifacts:
    paths:
      - app/build/outputs/

test:
  stage: test
  script:
    - echo "Running tests..."
  dependencies:
    - build

