image: openjdk:11
stages:
  - check_deleted_files
  #- build

#before_script:
 # - export ANDROID_HOME="$HOME/Library/Android/sdk"
 #  - bundle install

# build:
#  script:
#    - chmod +x ./gradlew
#    - echo "y" | sdkmanager --licenses                  not accepting licenses
#    - ./gradlew assembleDebug

check_deleted_files:
  stage: check_deleted_files
  script:
    - git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA > deleted_files.txt
    - if [ -s deleted_files.txt ]; then echo "Deleted files found:" && cat deleted_files.txt; else echo "No files deleted."; fi
  only:
    changes:
      - '**/*'

