stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.java.home=$CI_JAVA_HOME"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew --version
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

test:
  stage: test
  script:
    - echo "Running tests..."
  dependencies:
    - build

