image: openjdk:17
stages:
  - build
  - test


build:
  stage: build
  script:
    - ./gradlew --version
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

test:
  stage: test
  script:
    - echo "Running tests..."
  dependencies:
    - build

